class GuiSettings:
    COLOR_DISPLAY_Y_OFFSET = -25
    COLOR_DISPLAY_X_OFFSET = 25
    COLOR_SQUARE_SIZE = 10
    COLOR_DISPLAY_FONT_SIZE = 10

    COMMAND_DISPLAY_FONT_SIZE = 20
    COMMAND_DISPLAY_Y_POS = 25